run:
  tests: false
  skip-dirs:
  - vendor$
  modules-download-mode: vendor

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 80
    statements: 60
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: github.com/trevinteacutter/go-context-logger
  govet:
    enable-all: true
  lll:
    line-length: 120
    tab-width: 2
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
  - lll
  fast: false
